# The GroupName here is used to identify your company or business unit that
# created this webhook.
# For example, this may be "acme.mycompany.com".
# This name will need to be referenced in each Issuer's `webhook` stanza to
# inform cert-manager of where to send ChallengePayload resources in order to
# solve the DNS01 challenge.
# This group name should be **unique**, hence using your own company's domain
# here is recommended.
groupName: acme.ispmanager.com

certManager:
  namespace: cert-manager
  serviceAccountName: cert-manager
  install: false

replicaCount: 1

image:
  repository: globalartltd/cert-manager-webhook-ispmanager
  tag: latest
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

extraEnv: []
# - name: SOME_VAR
#   value: "some value"

service:
  type: ClusterIP
  port: 443
  annotations: {}

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

podAnnotations: {}

nodeSelector: {}

tolerations: []

affinity: {}

securityContext:
  runAsNonRoot: true
  runAsUser: 65534
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

podSecurityContext:
  fsGroup: 65534

# to avoid flowcontrol access errors if they are present
clusterRoleApiGroups:
  flowControlResources: false

webhook:
  mutating: false
  validating: true
  failurePolicy: Fail
  sideEffects: None
  admissionReviewVersions: ["v1", "v1beta1"]

apiVersionOverrides:
  flowcontrol: "flowcontrol.apiserver.k8s.io/v1"
