{{- if and .Values.license.value (not .Values.license.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "smev4-agent.fullname" . }}-license
  labels:
    {{- include "smev4-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.license.secretKey }}: {{ .Values.license.value | quote }}
{{- end }}
