{{- if not .Values.config.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "smev4-agent.fullname" . }}-config
  labels:
    {{- include "smev4-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  application.yml: |
{{ .Values.config.applicationYml | indent 4 }}
  customLogLevels.xml: |
{{ .Values.config.customLogLevelsXml | indent 4 }}
{{- end }}
